import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// Each sidebar backs one navbar tab: Docs, Tutorials, Reference, Roadmap.
const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    'getting-started',
    {
      type: 'category',
      label: 'Manual',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'manual'}],
    },
    'architecture',
  ],
  tutorialsSidebar: [{type: 'autogenerated', dirName: 'tutorials'}],
  referenceSidebar: [{type: 'autogenerated', dirName: 'reference'}],
  roadmapSidebar: ['roadmap'],
};

export default sidebars;
