import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// Each sidebar backs one navbar tab: Docs, Tutorials, Reference. The roadmap
// is a single doc in no sidebar, so it renders full width with only its
// table of contents.
const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    'principles',
    'getting-started',
    {
      type: 'category',
      label: 'Manual',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'manual'}],
    },
    'architecture',
    'built-on',
  ],
  tutorialsSidebar: [{type: 'autogenerated', dirName: 'tutorials'}],
  referenceSidebar: [{type: 'autogenerated', dirName: 'reference'}],
};

export default sidebars;
